input.onButtonPressed(Button.A, function on_button_pressed_a() {
    basic.showIcon(IconNames.Happy)
    music.play(music.stringPlayable("G D F A C E D C5 ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C D E F G A B C5 ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 A B G A F G E ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("G B A G C5 B A B ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("B A G A G F A C5 ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("E G A F F A G D ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C D F E E F D C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("D G A D A F D C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C D F B A E A B ", 120), music.PlaybackMode.UntilDone)
    basic.clearScreen()
})
input.onButtonPressed(Button.AB, function on_button_pressed_ab() {
    basic.showIcon(IconNames.Duck)
    music.play(music.stringPlayable("B G E C D F C B ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 B A G F E D C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 B A G F E D C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 B F E B E D A ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("F G D F D F E C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C B D G D F D A ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("G B A G C5 B A B ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 B C5 F E D A C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("E C F D F F C C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("B A G A G F A C5 ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("B A D G E D F G ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 E B D E A F C ", 120), music.PlaybackMode.UntilDone)
    basic.clearScreen()
})
input.onButtonPressed(Button.B, function on_button_pressed_b() {
    basic.showIcon(IconNames.Ghost)
    music.play(music.stringPlayable("D F A F E G E F ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("G B D F A G B G ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("B A F D E D D C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("B A F D E D D C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("F D G D A F D E ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("F D E C F E G C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("D B C5 G E B E C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("D B C5 G E B E C ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("D B F C A F G D ", 120), music.PlaybackMode.UntilDone)
    basic.clearScreen()
})
input.onLogoEvent(TouchButtonEvent.Pressed, function on_logo_pressed() {
    basic.showIcon(IconNames.Duck)
    music.play(music.stringPlayable("B G E C D F C B ", 120), music.PlaybackMode.UntilDone)
    basic.clearScreen()
})
